spring.application.name=movieBookingSystem


# Replace 'movie_db' with your actual database name
spring.datasource.url=jdbc:postgresql://localhost:5432/MovieBookingApp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialect is often auto-detected, but good to specify for Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8081

# JWT Properties
moviebooking.app.jwtSecret=abez9T82oJ6O1D0qW1y8sQ7n7L7R3F6E2V1p8N9gX5Z0Y4M2I6A4T1u3G5B2C1X8abez9T82oJ6O1D0qW1y8sQ7n7L7R3F6E2V1p8N9gX5Z0Y4M2I6A4T1u3G5B2C1X8
moviebooking.app.jwtExpirationMs=86400000
